### ISSUE TITLE
Could I know why use `camel/UAE_B74_2015` as reference?

### ISSUE THREAD

**Issue by liamxg** [nextstrain/mers#2]
Dear @genehack,

I hope this message finds you well.

Could I know why use `camel/UAE_B74_2015` as reference?

**Comment by genehack** [comment]
Hi @liamxg - 

This build was completed well before I joined the group. I've asked around, and nobody is quite sure why the person who set this up used that reference -- and they're no longer with the group. 

You might want to look at [this MERS repo](https://github.com/blab/mers-evolution/tree/main), which is more actively maintained. It uses [NC_019843](https://github.com/blab/mers-evolution/blob/main/nextstrain-build/phylogenetic/defaults/mers_reference.gb) as a reference.

**Comment by liamxg** [comment]
Dear @genehack,

Thanks for your reply and help.
